server:
  port: ${PORT:8081}

spring:
  application:
    name: money-tracker-api
    api-key: ${API_KEY:}
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
  datasource:
    url: ${DB_URL:jdbc:postgresql://ep-spring-moon-aph8nqmi-pooler.c-7.us-east-1.aws.neon.tech/neondb}
    username: ${DB_USERNAME:dongadmin}
    password: ${DB_PASSWORD:}


#    url: jdbc:h2:mem:testdb
#      driver-class-name: org.h2.Driver
#      username: sa
#      password:
#
#  h2:
#    console:
#      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        dialect: org.hibernate.dialect.H2Dialect

logging:
  level:
    org.hibernate.SQL: DEBUG